version: '3'

services:
  site:
    image: jekyll/jekyll:4.2.2
    command: jekyll serve --incremental --livereload --force_polling
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
